### ISSUE TITLE
npm run build 出来的并没有抽出相同的模块

### ISSUE THREAD

**Issue by hacke2** [lyyourc/webpack-code-splitting-demo#1]
这个是我的图

![image](https://cloud.githubusercontent.com/assets/6399899/25891614/452cb4e4-35a4-11e7-907d-814cd477e6c7.png)

这个是文章里的

![image](https://cloud.githubusercontent.com/assets/6399899/25891638/5c8f6924-35a4-11e7-8c7f-7f25f72151e5.png)

webpack 2.5.1

**Comment by hacke2** [comment]
webpack  版本问题

**Comment by blade254353074** [comment]
+1 新版本是有这个问题
