### ISSUE TITLE
关于import的Magic Comments的chunkname

### ISSUE THREAD

**Issue by devinRex** [lyyourc/webpack-code-splitting-demo#3]
请问下，这个不是webpack3才加的特性么，为什么项目在webpack2.4.1下能生效，我在2.6.0版本的webpack下试了build后chunk的名字也没变，百思不得其解

**Comment by lyyourc** [comment]
`2.4.1` 就已经支持了：https://github.com/webpack/webpack/releases?after=v2.4.1 。
至于 `2.6.0` 如果使用姿势正确但还是无效的话，估计是 bug 😂

**Comment by devinRex** [comment]
我再去研究一哈，多谢

**Comment by devinRex** [comment]
https://github.com/vuejs-templates/webpack/issues/730   原因出在这，应该是babel删除注释的操作进行的太早了。。
